name: Build_test_deploy_contracts

on:
  push:
    branches: ["main"]

  pull_request:
    types: [closed]
    branches:
      - main

  workflow_dispatch:  # allows manual triggering
  
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry v1.1.0
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.1.0

      - name: Run forge unit tests
        run: forge test --match-path "test/unit/*"

  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry v1.1.0
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.1.0

      - name: Run forge integration tests
        run: forge test --match-path "test/integration/*"
        
  deploy_to_sepolia:
      needs: [unit_tests, integration_tests]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Deploy contracts
          run: echo "Deploying contracts..."

