name: Deploy Express Server to Render

on:
  pull_request:
    types: [closed]
    branches:
      - main

  workflow_dispatch:  # allows manual triggering

jobs:
  deploy_express_server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js with version 23.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0

      - name: Trigger Render deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_BE_DEPLOY_HOOK}}


    


