name: Deploy Smart Contracts To Sepolia

on:
  workflow_run:
    workflows: ["Foundry_Unit_Integration_Tests"] # To make it linked 
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only if test passed
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy contracts
        run: echo "Deploying contracts..."
