name: Deploy Express to Render

on:
  pull_request:
    types: [closed]
    branches:
      - main

  workflow_dispatch:  # allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v23.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0

      - name: Install dependencies
        run: npm install

      # Optional: Lint
      # - name: Lint code
      #   run: npm run lint

      - name: Trigger deployment to Render for backend service
        run: curl -X POST ${{ secrets.RENDER_BE_DEPLOY_HOOK }}
