name: Foundry_Unit_Test

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v4

    - name: Use Foundry version 1.0.1
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: 1.0.1

    - name: Run tests
      run: forge test
