name: Foundry_Unit_Integration_Tests

on:
  push:
    branches: ["main"]

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry v1.1.0
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.1.0
      - name: Check current directory
        run: pwd
      
      - name: List test folder
        run: ls -R test/

      #  - name: Run forge unit tests
      #   run: forge test --match-path "test/unit/*"

  # integration_tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository with submodules
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: recursive

  #     - name: Install Foundry v1.1.0
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: v1.1.0

  #     - name: Run forge integration tests
        # run: forge test --match-path "test/integration/*"
        
