name: Build_test_deploy_contracts

on:
  pull_request:
    types: [closed]
    branches:
      - main

  workflow_dispatch:  # allows manual triggering
  
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry v1.1.0
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.1.0

      - name: Run forge unit tests
        run: forge test --match-path "test/unit/*"

  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry v1.1.0
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.1.0

      - name: Run forge integration tests
        run: forge test --match-path "test/integration/*"
  
  deploy_to_sepolia:
    - name: Set up environment variables
      run: |
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "SEPOLIA_RPC=${{ secrets.SEPOLIA_RPC }}" >> $GITHUB_ENV


    - name: Deploy contract to Sepolia
      run: |
        forge script script/DeploySepolia.s.sol:Deploy \
          --rpc-url $SEPOLIA_RPC \
          --private-key $PRIVATE_KEY \
          --broadcast \
          --verify
#         --etherscan-api-key ${{ secrets.ETHERSCAN_API_KEY }}  # Optional for verification

  testing_if_env_persists:
    - name: Just a test
      run: |
        echo "Lets see if it works: ${{ env.SEPOLIA_RPC}}"